/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tzjgfgfvrjhvqijamtdt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6amdmZ2Z2cmpodnFpamFtdGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzNTAzMzksImV4cCI6MjA3ODkyNjMzOX0.mZ4iCjIu68etcIoA2XxapTt-TE-mcYcRgnPPFkd0Dlw"